name: DAST Scan (ZAP)
#added dast scan file#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dast-scan:
    name: DAST Scan with OWASP ZAP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run vulnerable app (Juice Shop)
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Wait for app to be ready
        run: sleep 15

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'

