name: DevSecOps Demo Pipeline
permissions:
  contents: read


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run DevSecOps Job
        run: echo "DevSecOps Pipeline Triggered Successfully!"
