name: Trivy Image Scan

on:
  workflow_dispatch:  # Manual trigger

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Pull Juice Shop Docker image
      run: docker pull bkimminich/juice-shop

    - name: Trivy scan Juice Shop image
      run: trivy image --severity CRITICAL,HIGH --format table --output trivy-image-report.txt bkimminich/juice-shop

    - name: Upload Trivy report
      uses: actions/upload-artifact@v4   # <-- Updated to v4
      with:
        name: trivy-image-report
        path: trivy-image-report.txt

