name: Trivy Image Scan

on:
  workflow_dispatch:

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.deb
          sudo dpkg -i trivy_Linux-64bit.deb

      # Step 3: Pull Juice Shop Docker image
      - name: Pull Juice Shop Docker image
        run: docker pull bkimminich/juice-shop:latest

      # Step 4: Scan Docker image and save output
      - name: Scan Docker Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --format table bkimminich/juice-shop:latest | tee trivy-report.txt

      # Step 5: Upload Trivy report as artifact (fixed v4)
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

